### ISSUE TITLE
Saving hangs

### ISSUE THREAD

**Issue by Ambrevar** [walseb/blimp#2]
Saving (using `C-x C-s`) an image buffer after a blimp transformation (e.g. rotate) seems to hang forever.

I haven't investigated the issue at all for the moment.  Can anyone reproduce?

**Comment by walseb** [comment]
I can't reproduce this with emacs -q (if you attempt this, remember to pull the latest version of this package because I just fixed a dependency that is never loaded by default and prevents the user from entering a command parameter) or my personal config. See if you have something that runs on save (e.g. the "write-contents-functions" hook) like a formatter, white space remover, etc

**Comment by Ambrevar** [comment]
Found the issue: I have `delete-trailing-whitespace` in `before-save-hook`.  This hangs Emacs.  What do you suggest against this?  Should we fix this upstream?

Unrelated, but you need to `require` some more packages:
    password-read, string-join, string-empty-p

**Comment by walseb** [comment]
> Found the issue: I have delete-trailing-whitespace in before-save-hook. This hangs Emacs. What do you suggest against this? Should we fix this upstream?

I would recommend [whitespace-cleanup-mode](https://melpa.org/#/whitespace-cleanup-mode) or running `delete-trailing-whitespace` with a hotkey.

> Unrelated, but you need to require some more packages: password-read, string-join, string-empty-p
Yeah 

Thanks! I fixed the last two a bit earlier today but forgot about password-read

**Comment by Ambrevar** [comment]
I found about the missing requires with `(async-byte-recompile-directory ".")`, it's very useful for detecting lots of errors.

**Comment by Ambrevar** [comment]
I've reported the issue upstream.

**Comment by Ambrevar** [comment]
Upstream fixed it in development version.
