### ISSUE TITLE
Command information not visible using ivy and eimp dependency

### ISSUE THREAD

**Issue by technician77** [walseb/blimp#4]
I just would like to see the IM command information, that can be seen in your screenshots. I'm using ivy but I can't see anything. Any idea?

EImp is from 2012. Is it still maintained? Is it a good idea to have such an old package as dependency? I'm not a coder it just seems odd to me.

By the way `setq eimp-enable-undo t` is great. It enables use of undo-tree-undo and redo for images. Maybe you should mention it in your readme since the default is nil.

**Comment by walseb** [comment]
> I just would like to see the IM command information, that can be seen in your screenshots. I'm using ivy but I can't see anything. Any idea?

I did `emacs -q` and loaded up this config
```emacs-lisp
(package-initialize)
(use-package ivy)

(ivy-mode 1)

(use-package blimp)

(require 'blimp)
(add-hook 'image-mode-hook 'blimp-mode)
```
and was able to replicate the screenshot. If you are referring to auto completion, maybe you are using commands that don't support any selectable candidates (because they have an endless amount of possible inputs, such as selecting a position on the image, etc). Do you still have this problem when entering `compress` like in the screenshot?

> EImp is from 2012. Is it still maintained? Is it a good idea to have such an old package as dependency? I'm not a coder it just seems odd to me.

I'm not sure if it's maintained (if it isn't and it gets broken, I will probably maintain it), but it's solid and I have had no problems with it. Replacing it would a huge task that I don't think is worth doing. It does however use a lot of obsolete commands that I fixed in an earlier version of this package when I had it bundled, but I haven't bothered sending the changes I made to upstream yet (you can do this if want to though, but be careful I also removed most eimp interactive commands because blimp already provides them).

> By the way setq eimp-enable-undo t is great. It enables use of undo-tree-undo and redo for images. Maybe you should mention it in your readme since the default is nil.

Thanks! I will.

**Comment by technician77** [comment]
Now I see, you only get the info on the second level, if there is one. Would it be possible to get the info on the first level, directly when you say "blimp-interface" oder "blimp-interface-execute? To me it would make more sense to me it terms of discoverability.

Well, if you say eimp is still good for the job you might bring it up to 2018 standard. I would help but I belong to the rare species of emacs users that has no knowlege of programming. I don't like touching things that I have no knowlege of - it might end up broken.

Let's assume IM gets a new operation. Can you integrate that in blimp or will that need to be integrated in eimp too? If the latter one I assume there is quite a delta between the operations in eimp and the possible operations in IM or are they on par? I just wonder because IM is quite often updated.

**Comment by walseb** [comment]
> Now I see, you only get the info on the second level, if there is one. Would it be possible to get the info on the first level, directly when you say "blimp-interface" oder "blimp-interface-execute? To me it would make more sense to me it terms of discoverability.

You should get a list of all possible commands right after doing `blimp-interface` or `blimp-interface-execute`, if you don't it's probably a problem with your config since I was able to get it with `emacs -q` and the config above. Were you able to get completion on the second level? Also, make sure you are running the latest version of blimp.

> Let's assume IM gets a new operation. Can you integrate that in blimp or will that need to be integrated in eimp too? If the latter one I assume there is quite a delta between the operations in eimp and the possible operations in IM or are they on par? I just wonder because IM is quite often updated.

Yes, `eimp.el` only passes through the commanads to imagemagick (and handles where imagemagick outputs the resulting image) so you would only have to update `blimp` in this case

**Comment by technician77** [comment]
That's what I get:
![image](https://user-images.githubusercontent.com/18722291/45327653-ada7b980-b558-11e8-96fc-ef5f0cfd0b8f.png)

**Comment by walseb** [comment]
Oh I see what you mean! Yeah, you only get to see autocompletion options on the second level because if I inserted all second level commands into the first level to show a preview, ido (or any kind of vertically stacked completion framework) would be ususable since it displays the candidates vertically so you would probably only see the first candidate on small displays. To fix this you would have to implement a mechanism that detected which completion framework the user uses and then either display the extra info (maybe the description of the command and available autocompletion options) or display it normally.
